# Generated by Django 4.2.7 on 2025-06-08 08:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "codigo",
                    models.CharField(max_length=10, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "categoria_padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategorias",
                        to="core.categoriaproducto",
                        verbose_name="Categoría Padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Producto",
                "verbose_name_plural": "Categorías de Productos",
                "db_table": "core_categoria_producto",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave",
                    models.CharField(max_length=100, unique=True, verbose_name="Clave"),
                ),
                ("valor", models.TextField(verbose_name="Valor")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("string", "Texto"),
                            ("integer", "Número Entero"),
                            ("decimal", "Número Decimal"),
                            ("boolean", "Verdadero/Falso"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="Tipo de Dato",
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sistema",
                "verbose_name_plural": "Configuraciones del Sistema",
                "db_table": "core_configuracion_sistema",
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "ruc",
                    models.CharField(
                        help_text="Registro Único de Contribuyente",
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El RUC debe tener exactamente 11 dígitos",
                                regex="^\\d{11}$",
                            )
                        ],
                        verbose_name="RUC",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=200, verbose_name="Razón Social"),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre Comercial"
                    ),
                ),
                ("direccion", models.TextField(verbose_name="Dirección")),
                (
                    "ubigeo",
                    models.CharField(
                        help_text="Código de ubigeo INEI de 6 dígitos",
                        max_length=6,
                        verbose_name="Ubigeo INEI",
                    ),
                ),
                ("distrito", models.CharField(max_length=100, verbose_name="Distrito")),
                (
                    "provincia",
                    models.CharField(max_length=100, verbose_name="Provincia"),
                ),
                (
                    "departamento",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Formato de teléfono inválido",
                                regex="^(\\+51\\s?)?(\\d{2,3}\\s?)?[\\d\\s-]{6,9}$",
                            )
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("pagina_web", models.URLField(blank=True, verbose_name="Página Web")),
                (
                    "plan_cuentas",
                    models.CharField(
                        choices=[
                            ("PCGE", "Plan Contable General Empresarial"),
                            ("PCGR", "Plan Contable General Revisado"),
                        ],
                        default="PCGE",
                        max_length=10,
                        verbose_name="Plan de Cuentas",
                    ),
                ),
                (
                    "moneda_base",
                    models.CharField(
                        choices=[
                            ("PEN", "Nuevos Soles"),
                            ("USD", "Dólares Americanos"),
                            ("EUR", "Euros"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Moneda Base",
                    ),
                ),
                (
                    "regimen_tributario",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Régimen General"),
                            ("ESPECIAL", "Régimen Especial de Renta"),
                            ("MYPE", "Régimen MYPE Tributario"),
                            ("RUS", "Nuevo RUS"),
                        ],
                        default="GENERAL",
                        max_length=50,
                        verbose_name="Régimen Tributario",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="empresas/logos/",
                        verbose_name="Logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "core_empresa",
            },
        ),
        migrations.CreateModel(
            name="Moneda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("codigo", models.CharField(max_length=3, unique=True)),
                ("nombre", models.CharField(max_length=50)),
                ("simbolo", models.CharField(max_length=5)),
            ],
            options={
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
                "db_table": "core_moneda",
            },
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Unidad de Medida",
                "verbose_name_plural": "Unidades de Medida",
                "db_table": "core_unidad_medida",
            },
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("codigo", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.TextField(blank=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("es_principal", models.BooleanField(default=False)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursales",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
                "db_table": "core_sucursal",
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "ruc",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El RUC debe tener exactamente 11 dígitos",
                                regex="^\\d{11}$",
                            )
                        ],
                        verbose_name="RUC",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=200, verbose_name="Razón Social"),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre Comercial"
                    ),
                ),
                ("direccion", models.TextField(verbose_name="Dirección")),
                (
                    "ubigeo",
                    models.CharField(blank=True, max_length=6, verbose_name="Ubigeo"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Formato de teléfono inválido",
                                regex="^(\\+51\\s?)?(\\d{2,3}\\s?)?[\\d\\s-]{6,9}$",
                            )
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "contacto_principal",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contacto Principal"
                    ),
                ),
                (
                    "dias_pago",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Días de Pago"
                    ),
                ),
                (
                    "descuento_obtenido",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Descuento Obtenido (%)",
                    ),
                ),
                (
                    "activo_comercial",
                    models.BooleanField(
                        default=True, verbose_name="Activo Comercialmente"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "db_table": "core_proveedor",
                "indexes": [
                    models.Index(fields=["ruc"], name="core_provee_ruc_d858ab_idx"),
                    models.Index(
                        fields=["razon_social"], name="core_provee_razon_s_8c2ade_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI - Documento Nacional de Identidad"),
                            ("RUC", "RUC - Registro Único de Contribuyente"),
                            ("CE", "CE - Carnet de Extranjería"),
                            ("PASSPORT", "Pasaporte"),
                            ("OTROS", "Otros documentos"),
                        ],
                        default="DNI",
                        max_length=10,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=20, verbose_name="Número de Documento"),
                ),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[
                            ("PERSONA_NATURAL", "Persona Natural"),
                            ("PERSONA_JURIDICA", "Persona Jurídica"),
                            ("NO_DOMICILIADO", "No Domiciliado"),
                        ],
                        default="PERSONA_NATURAL",
                        max_length=20,
                        verbose_name="Tipo de Cliente",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        max_length=200, verbose_name="Razón Social / Nombres"
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nombres"
                    ),
                ),
                (
                    "apellido_paterno",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Apellido Paterno"
                    ),
                ),
                (
                    "apellido_materno",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Apellido Materno"
                    ),
                ),
                ("direccion", models.TextField(verbose_name="Dirección")),
                (
                    "ubigeo",
                    models.CharField(blank=True, max_length=6, verbose_name="Ubigeo"),
                ),
                (
                    "distrito",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Distrito"
                    ),
                ),
                (
                    "provincia",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Provincia"
                    ),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Formato de teléfono inválido",
                                regex="^(\\+51\\s?)?(\\d{2,3}\\s?)?[\\d\\s-]{6,9}$",
                            )
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "limite_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Límite de Crédito",
                    ),
                ),
                (
                    "dias_credito",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Días de Crédito"
                    ),
                ),
                (
                    "descuento_maximo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Descuento Máximo (%)",
                    ),
                ),
                (
                    "bloqueado",
                    models.BooleanField(
                        default=False, verbose_name="Cliente Bloqueado"
                    ),
                ),
                (
                    "fecha_bloqueo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Bloqueo"
                    ),
                ),
                (
                    "motivo_bloqueo",
                    models.TextField(blank=True, verbose_name="Motivo de Bloqueo"),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "core_cliente",
                "indexes": [
                    models.Index(
                        fields=["numero_documento"],
                        name="core_client_numero__d0bea7_idx",
                    ),
                    models.Index(
                        fields=["razon_social"], name="core_client_razon_s_665cdc_idx"
                    ),
                    models.Index(
                        fields=["tipo_cliente"], name="core_client_tipo_cl_a52bcf_idx"
                    ),
                ],
                "unique_together": {("tipo_documento", "numero_documento")},
            },
        ),
        migrations.CreateModel(
            name="TipoCambio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha", models.DateField()),
                ("valor_compra", models.DecimalField(decimal_places=4, max_digits=10)),
                ("valor_venta", models.DecimalField(decimal_places=4, max_digits=10)),
                ("fuente", models.CharField(default="SUNAT", max_length=50)),
                (
                    "moneda_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cambios_destino",
                        to="core.moneda",
                    ),
                ),
                (
                    "moneda_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cambios_origen",
                        to="core.moneda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Cambio",
                "verbose_name_plural": "Tipos de Cambio",
                "db_table": "core_tipo_cambio",
                "unique_together": {("moneda_origen", "moneda_destino", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "codigo_barras",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Código de Barras",
                    ),
                ),
                (
                    "codigo_sunat",
                    models.CharField(
                        blank=True,
                        help_text="Código de producto según catálogo SUNAT",
                        max_length=10,
                        verbose_name="Código SUNAT",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "tipo_producto",
                    models.CharField(
                        choices=[("BIEN", "Bien"), ("SERVICIO", "Servicio")],
                        default="BIEN",
                        max_length=10,
                        verbose_name="Tipo de Producto",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        default="NIU",
                        help_text="Código según catálogo SUNAT (NIU=Unidad)",
                        max_length=10,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "precio_compra",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                        verbose_name="Precio de Compra",
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                        verbose_name="Precio de Venta",
                    ),
                ),
                (
                    "precio_venta_minimo",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                        verbose_name="Precio de Venta Mínimo",
                    ),
                ),
                (
                    "tipo_afectacion_igv",
                    models.CharField(
                        choices=[
                            ("10", "Gravado - Operación Onerosa"),
                            ("11", "Gravado - Retiro por premio"),
                            ("12", "Gravado - Retiro por donación"),
                            ("13", "Gravado - Retiro"),
                            ("14", "Gravado - Retiro por publicidad"),
                            ("15", "Gravado - Bonificaciones"),
                            ("16", "Gravado - Retiro por entrega a trabajadores"),
                            ("17", "Gravado - IVAP"),
                            ("20", "Exonerado - Operación Onerosa"),
                            ("21", "Exonerado - Transferencia Gratuita"),
                            ("30", "Inafecto - Operación Onerosa"),
                            ("31", "Inafecto - Retiro por Bonificación"),
                            ("32", "Inafecto - Retiro"),
                            ("33", "Inafecto - Retiro por Muestras Médicas"),
                            ("34", "Inafecto - Retiro por Convenio Colectivo"),
                            ("35", "Inafecto - Retiro por premio"),
                            ("36", "Inafecto - Retiro por publicidad"),
                            ("40", "Exportación de Bienes o Servicios"),
                        ],
                        default="10",
                        max_length=2,
                        verbose_name="Tipo de Afectación IGV",
                    ),
                ),
                (
                    "incluye_igv",
                    models.BooleanField(
                        default=True, verbose_name="Precio incluye IGV"
                    ),
                ),
                (
                    "controla_stock",
                    models.BooleanField(default=True, verbose_name="Controla Stock"),
                ),
                (
                    "stock_actual",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                        verbose_name="Stock Actual",
                    ),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                        verbose_name="Stock Mínimo",
                    ),
                ),
                (
                    "stock_maximo",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000"))
                        ],
                        verbose_name="Stock Máximo",
                    ),
                ),
                (
                    "marca",
                    models.CharField(blank=True, max_length=100, verbose_name="Marca"),
                ),
                (
                    "modelo",
                    models.CharField(blank=True, max_length=100, verbose_name="Modelo"),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="productos/imagenes/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "activo_venta",
                    models.BooleanField(default=True, verbose_name="Activo para Venta"),
                ),
                (
                    "activo_compra",
                    models.BooleanField(
                        default=True, verbose_name="Activo para Compra"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.categoriaproducto",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "core_producto",
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="core_produc_codigo_41dc3f_idx"
                    ),
                    models.Index(
                        fields=["codigo_barras"], name="core_produc_codigo__3bd02c_idx"
                    ),
                    models.Index(
                        fields=["nombre"], name="core_produc_nombre_f34c30_idx"
                    ),
                    models.Index(
                        fields=["categoria"], name="core_produc_categor_5756ff_idx"
                    ),
                    models.Index(
                        fields=["activo_venta"], name="core_produc_activo__ba781b_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="categoriaproducto",
            index=models.Index(fields=["codigo"], name="core_catego_codigo_647817_idx"),
        ),
        migrations.AddIndex(
            model_name="categoriaproducto",
            index=models.Index(fields=["nombre"], name="core_catego_nombre_a1c881_idx"),
        ),
    ]
