# Generated by Django 4.2.7 on 2025-06-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="departamento",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sucursal",
            name="distrito",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sucursal",
            name="provincia",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sucursal",
            name="ubigeo",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
