# Generated by Django 4.2.7 on 2025-06-08 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "email",
                    models.EmailField(
                        help_text="Dirección de correo electrónico para login",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Nombre único de usuario",
                        max_length=50,
                        unique=True,
                        verbose_name="Nombre de Usuario",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI - Documento Nacional de Identidad"),
                            ("CE", "CE - Carnet de Extranjería"),
                            ("PASSPORT", "Pasaporte"),
                        ],
                        default="DNI",
                        max_length=10,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Documento"
                    ),
                ),
                ("nombres", models.CharField(max_length=100, verbose_name="Nombres")),
                (
                    "apellido_paterno",
                    models.CharField(max_length=50, verbose_name="Apellido Paterno"),
                ),
                (
                    "apellido_materno",
                    models.CharField(max_length=50, verbose_name="Apellido Materno"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=100, verbose_name="Cargo"),
                ),
                (
                    "area",
                    models.CharField(blank=True, max_length=100, verbose_name="Área"),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Ingreso",
                    ),
                ),
                (
                    "es_admin_empresa",
                    models.BooleanField(
                        default=False,
                        help_text="Puede gestionar configuraciones de la empresa",
                        verbose_name="Administrador de Empresa",
                    ),
                ),
                (
                    "puede_aprobar_facturas",
                    models.BooleanField(
                        default=False, verbose_name="Puede Aprobar Facturas"
                    ),
                ),
                (
                    "limite_descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Descuento máximo que puede aplicar",
                        max_digits=5,
                        verbose_name="Límite de Descuento (%)",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Puede acceder al admin de Django",
                        verbose_name="Es Staff",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_ultimo_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Login"
                    ),
                ),
                (
                    "requiere_cambio_password",
                    models.BooleanField(
                        default=True, verbose_name="Requiere Cambio de Password"
                    ),
                ),
                (
                    "fecha_expiracion_password",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Expiración de Password",
                    ),
                ),
                (
                    "intentos_login_fallidos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Intentos de Login Fallidos"
                    ),
                ),
                (
                    "bloqueado_hasta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bloqueado Hasta"
                    ),
                ),
                (
                    "tema_interfaz",
                    models.CharField(
                        choices=[
                            ("light", "Claro"),
                            ("dark", "Oscuro"),
                            ("auto", "Automático"),
                        ],
                        default="auto",
                        max_length=20,
                        verbose_name="Tema de Interfaz",
                    ),
                ),
                (
                    "idioma",
                    models.CharField(
                        choices=[("es", "Español"), ("en", "English")],
                        default="es",
                        max_length=5,
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "zona_horaria",
                    models.CharField(
                        default="America/Lima",
                        max_length=50,
                        verbose_name="Zona Horaria",
                    ),
                ),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="usuarios/fotos/",
                        verbose_name="Foto de Perfil",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios_usuario",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del Rol"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "es_rol_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Los roles del sistema no pueden ser eliminados",
                        verbose_name="Es Rol del Sistema",
                    ),
                ),
                (
                    "permisos_especiales",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Permisos específicos del sistema FELICITA",
                        verbose_name="Permisos Especiales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "usuarios_rol",
            },
        ),
        migrations.CreateModel(
            name="PermisoPersonalizado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del Permiso"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código del Permiso"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("facturacion", "Facturación"),
                            ("inventario", "Inventario"),
                            ("contabilidad", "Contabilidad"),
                            ("punto_venta", "Punto de Venta"),
                            ("reportes", "Reportes"),
                            ("configuracion", "Configuración"),
                            ("usuarios", "Usuarios"),
                            ("clientes", "Clientes"),
                            ("productos", "Productos"),
                        ],
                        max_length=20,
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("crear", "Crear"),
                            ("leer", "Leer"),
                            ("actualizar", "Actualizar"),
                            ("eliminar", "Eliminar"),
                            ("aprobar", "Aprobar"),
                            ("anular", "Anular"),
                            ("imprimir", "Imprimir"),
                            ("exportar", "Exportar"),
                            ("configurar", "Configurar"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "es_critico",
                    models.BooleanField(
                        default=False,
                        help_text="Permisos críticos requieren doble confirmación",
                        verbose_name="Es Crítico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso Personalizado",
                "verbose_name_plural": "Permisos Personalizados",
                "db_table": "usuarios_permiso_personalizado",
                "unique_together": {("modulo", "accion")},
            },
        ),
        migrations.CreateModel(
            name="UsuarioRol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Asignación",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "asignado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles_asignados_por_mi",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado Por",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios_asignados",
                        to="usuarios.rol",
                        verbose_name="Rol",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario-Rol",
                "verbose_name_plural": "Usuarios-Roles",
                "db_table": "usuarios_usuario_rol",
                "unique_together": {("usuario", "rol")},
            },
        ),
        migrations.CreateModel(
            name="SesionUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_sesion",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Token de Sesión"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Inicio"
                    ),
                ),
                (
                    "fecha_ultimo_acceso",
                    models.DateTimeField(auto_now=True, verbose_name="Último Acceso"),
                ),
                (
                    "fecha_cierre",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Cierre"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Dirección IP"),
                ),
                ("user_agent", models.TextField(verbose_name="User Agent")),
                (
                    "dispositivo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Dispositivo"
                    ),
                ),
                (
                    "navegador",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Navegador"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación Aproximada"
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(default=True, verbose_name="Sesión Activa"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Usuario",
                "verbose_name_plural": "Sesiones de Usuarios",
                "db_table": "usuarios_sesion_usuario",
                "indexes": [
                    models.Index(
                        fields=["usuario", "activa"],
                        name="usuarios_se_usuario_b6157b_idx",
                    ),
                    models.Index(
                        fields=["fecha_inicio"], name="usuarios_se_fecha_i_f7076b_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="usuarios_se_ip_addr_782d62_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LogActividadUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de Sesión"),
                            ("logout", "Cierre de Sesión"),
                            ("crear", "Crear Registro"),
                            ("actualizar", "Actualizar Registro"),
                            ("eliminar", "Eliminar Registro"),
                            ("ver", "Ver Registro"),
                            ("exportar", "Exportar Datos"),
                            ("imprimir", "Imprimir"),
                            ("configurar", "Configurar Sistema"),
                            ("aprobar", "Aprobar Documento"),
                            ("anular", "Anular Documento"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                ("modulo", models.CharField(max_length=50, verbose_name="Módulo")),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID del Objeto"
                    ),
                ),
                (
                    "objeto_tipo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo de Objeto"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Dirección IP"),
                ),
                (
                    "datos_adicionales",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos Adicionales"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Actividad",
                "verbose_name_plural": "Logs de Actividades",
                "db_table": "usuarios_log_actividad_usuario",
                "indexes": [
                    models.Index(
                        fields=["usuario", "fecha"],
                        name="usuarios_lo_usuario_5020a1_idx",
                    ),
                    models.Index(
                        fields=["accion"], name="usuarios_lo_accion_b17ee5_idx"
                    ),
                    models.Index(
                        fields=["modulo"], name="usuarios_lo_modulo_5bee5b_idx"
                    ),
                    models.Index(fields=["fecha"], name="usuarios_lo_fecha_530cb0_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["email"], name="usuarios_us_email_41a027_idx"),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["username"], name="usuarios_us_usernam_a1b21e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["numero_documento"], name="usuarios_us_numero__b22c5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["empresa"], name="usuarios_us_empresa_a4362a_idx"
            ),
        ),
    ]
